---
versions:
    release:
        version_number: "3.2" # change this at release time
        r_url: "http://cran.fhcrc.org/src/base/R-latest.tar.gz"
        parent: "rocker/rstudio"
        use_r_devel: false # should always be false
    devel:
        version_number: "3.3" # change this at release time
        ## IMPORTANT: Change r_url at release time if new bioc devel does(not) use R-devel
        parent: "rocker/rstudio-daily"# specify latest?
        use_r_devel: true # true half the year
        # The following variable (use_numbered_branch) is only relevant if
        # use_r_devel is true.
        # use_numbered_branch should be false OR should be the (quoted) version number from
        # which to pull R. Set to false if you want to use the default R installed
        # by rocker, which pulls from trunk. Or set to a number (i.e. 3.2) to
        # install R from that branch. This is appropriate when R-devel becomes R-alpha.
        # For example, around March 19th, 2015, an R-3-2-branch was created and
        # the R in trunk became R-3.3. However, the contemporaneous Bioconductor
        # devel branch uses R-3.2, NOT 3.3, so we would set the below variable
        # to "3.2" (be sure to quote the value so it's forced to be a string).
        use_numbered_branch: "3.3"

containers: # FIXME (?) rename this to 'images' (?)
    base:
        parent: bogus
    core:
        parent: bioconductor/base
    flow:
        parent: bioconductor/core
        biocViews:
            - FlowCytometry
    microarray:
        parent: bioconductor/core
        biocViews:
            - Microarray
    sequencing:
        parent: bioconductor/core
        biocViews:
            - Sequencing
    proteomics:
        parent: bioconductor/core
        biocViews:
            - Proteomics
    metabolomics:
        parent: bioconductor/core
        biocViews:
            - Metabolomics
