---
versions:
    release:
        version_number: "3.0" # change this at release time
        r_url: "http://cran.fhcrc.org/src/base/R-latest.tar.gz"
        parent: "rocker/rstudio"
        use_r_devel: false # should always be false
    devel:
        version_number: "3.1" # change this at release time
        ## IMPORTANT: Change r_url at release time if new bioc devel does(not) use R-devel
        parent: "rocker/rstudio-daily"# specify latest?   
        use_r_devel: true # true half the year
containers: # FIXME (?) rename this to 'images' (?)
    base:
        parent: bogus
    core:
        parent: bioconductor/base
    flow:
        parent: bioconductor/core
        biocViews: 
            - FlowCytometry
    microarray:
        parent: bioconductor/core
        biocViews:
            - Microarray
    sequencing:
        parent: bioconductor/core
        biocViews:
            - Sequencing
    proteomics:
        parent: bioconductor/core
        biocViews:
            - Proteomics
