---
devel_base:
    source_dir: src/base
    out_dir: out/devel_base
    data:
        parent: "ubuntu:14.04"
        image_name: "bioconductor/devel_base"
        r_url: "http://s3.amazonaws.com/r-devel-source/R-devel.tar.gz" # gets updated daily by cron
        bioc_version: "3.1" # change me at release time
devel_core:
    source_dir: src/core
    out_dir: out/devel_core
    data:
        parent: "bioconductor/devel_base"
        image_name: "bioconductor/devel_core"
devel_flowCytometry:
    source_dir: src/flowCytometry
    out_dir: out/devel_flowCytometry
    data:
        parent: bioconductor/devel_core
        image_name: bioconductor/devel_flowcytometry
        bioc_version: "3.1" # change me at release time
release_base:
    source_dir: src/base
    out_dir: out/release_base
    data:
        parent: "ubuntu:14.04"
        image_name: "bioconductor/release_base"
        r_url: "http://cran.fhcrc.org/src/base/R-latest.tar.gz"
        bioc_version: "3.0" # change me at release time
release_core:
    source_dir: src/core
    out_dir: out/release_core
    data:
        parent: "bioconductor/release_base"
        image_name: "bioconductor/release_core"
release_flowCytometry:
    source_dir: src/flowCytometry
    out_dir: out/release_flowCytometry
    data:
        parent: bioconductor/release_core
        image_name: bioconductor/release_flowcytometry
        bioc_version: "3.0" # change me at release time
