---
devel_base:
    source_dir: src/base
    out_dir: out/devel_base
    data:
        parent: "ubuntu:14.04"
        image_name: "bioconductor/devel_base"
        r_url: "http://s3.amazonaws.com/r-devel-source/R-devel.tar.gz" # gets updated daily by cron
        bioc_version: "3.1" # change me at release time
devel_core:
    source_dir: src/core
    out_dir: out/devel_core
    data:
        parent: "bioconductor/devel_base"
        image_name: "bioconductor/devel_core"
devel_flow:
    source_dir: src/flow
    out_dir: out/devel_flow
    data:
        parent: bioconductor/devel_core
        image_name: bioconductor/devel_flow
        bioc_version: "3.1" # change me at release time
        biocViews: 
            - FlowCytometry
devel_microarray:
    source_dir: src/microarray
    out_dir: out/devel_microarray
    data:
        parent: bioconductor/devel_core
        image_name: bioconductor/devel_microarray
        bioc_version: "3.1" # change me at release time
        biocViews:
            - Microarray
devel_sequencing:
    source_dir: src/sequencing
    out_dir: out/devel_sequencing
    data:
        parent: bioconductor/devel_core
        image_name: bioconductor/devel_sequencing
        bioc_version: "3.1" # change me at release time
        biocViews:
            - Sequencing
release_base:
    source_dir: src/base
    out_dir: out/release_base
    data:
        parent: "ubuntu:14.04"
        image_name: "bioconductor/release_base"
        r_url: "http://cran.fhcrc.org/src/base/R-latest.tar.gz"
        bioc_version: "3.0" # change me at release time
release_core:
    source_dir: src/core
    out_dir: out/release_core
    data:
        parent: "bioconductor/release_base"
        image_name: "bioconductor/release_core"
release_flow:
    source_dir: src/flow
    out_dir: out/release_flow
    data:
        parent: bioconductor/release_core
        image_name: bioconductor/release_flow
        bioc_version: "3.0" # change me at release time
        biocViews:
            - FlowCytometry
release_microarray:
    source_dir: src/microarray
    out_dir: out/release_microarray
    data:
        parent: bioconductor/release_core
        image_name: bioconductor/release_microarray
        bioc_version: "3.0" # change me at release time
        biocViews:
            - Microarray
release_variants:
    source_dir: src/variants
    out_dir: out/release_variants
    data:
        parent: bioconductor/release_core
        image_name: bioconductor/release_variants
        bioc_version: "3.0" # change me at release time
        biocViews:
            - VariantAnnotation
            - VariantDetection
release_sequencing:
    source_dir: src/sequencing
    out_dir: out/release_sequencing
    data:
        parent: bioconductor/release_core
        image_name: bioconductor/release_sequencing
        bioc_version: "3.0" # change me at release time
        biocViews:
            - Sequencing
